name: Run CI/CD on Main Branch

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (Copying) repositary
        uses: actions/checkout@v4
        
      - name: Build Docker Images
        run: |
          docker compose up -d --build

      - name: Start Docker Services
        run: |
          docker compose up -d --wait

      - name: List Files in Frontend Container
        run: |
          docker compose exec -T frontend ls

      - name: Run the tests
        run: |
          docker compose exec -T backend pytest

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (Copying) repositary
        uses: actions/checkout@v4

      
